title: Colour change
hero_image: images/banner.png
description:
version: 4
listed: false
copyedit: false
last_tested: "2018-12-06"
steps:
  - title: Introduction
  - title: Changing a colour
  - title: Choosing a tolerance
  - title: Creating a tool
  - title: Challenge: "improve your tool"
    challenge: true
